<table>
        <tr>
            <td class="table_header">Название</td>
            <td class="table_header">Рзмер<br>световые годы</td>
            <td class="table_header">Тип</td>
        </tr>
        <?
            foreach ($galaxis as $galaxy) {
                $galaxy_id = $galaxy->_id;
				$galaxy_name = $galaxy->name;
				$galaxy_size = $galaxy->size;
				$galaxy_type = TypeOfGalaxy::findById($galaxy->type_id)->name;
				include "is_string.phtml";
			}
        ?>
</table>