							<form name="fupd" action="http://space.tp/mishaapi/upded" method="post">
		            			<input class="galaxyin" type="hidden" name="table" value="car">
		            			<input class="galaxyin" type="hidden" name="id" value="<?=$data_g->id;?>">
		            			<label>Марка автомобиля</label><br />
								<select name="dealer" class="galaxyin">
									<option disabled="disabled">Выберете Автодилера</option>
		            		<?
		            		for ($i = 1; $i > 0; $i++) 
		            		{ 
		            			$out_dealer = $this->curvl("dealer", $i);
		            			if ($out_dealer->status == "Найдено" && count($out->data) != 0)
		            			{

				            		foreach ($out_dealer->data as $data) {
				            			if ($data_g->dealer == $data->name) {
				            				?>
										    	<option value="<?=$data->id?>" selected="selected"><?=$data->name?></option>
										    <?
				            			}
				            			else
				            			{
										    ?>
										    	<option value="<?=$data->id?>"><?=$data->name?></option>
										    <?
										}
								    }
								}
								else
									break;
		            		}				    
						    ?>
						    </select>
						    <br />
						    <label>Водитель</label><br />
						    <select name="driver" class="galaxyin">
								<option disabled="disabled">Выберете водителя</option>
							<?
		            		for ($i=1; $i > 0; $i++) 
		            		{ 
		            			$out = $this->curvl("driver", $i);
		            			if ($out->status == "Найдено" && count($out->data) != 0)
		            			{
				            		foreach ($out->data as $data) {
				            			if ($data_g->driver == $data->name) {
				            				?>
										    	<option value="<?=$data->id?>" selected="selected"><?=$data->name?></option>
										    <?
				            			}
				            			else
				            			{
										    ?>
										    	<option value="<?=$data->id?>"><?=$data->name?></option>
										    <?
										}
								    }
								}
								else
									break;
		            		}				    
						    ?>
						    </select>
						    <br />
						    <label>Владелец</label><br />
						    <select name="owner" class="galaxyin">
								<option disabled="disabled">Выберете владельца</option>
							<?
		            		for ($i=1; $i > 0; $i++) 
		            		{ 
		            			$out = $this->curvl("owner", $i);
		            			if ($out->status == "Найдено" && count($out->data) != 0)
		            			{
				            		foreach ($out->data as $data) {
								    if ($data_g->owner == $data->name) {
				            				?>
										    	<option value="<?=$data->id?>" selected="selected"><?=$data->name?></option>
										    <?
				            			}
				            			else
				            			{
										    ?>
										    	<option value="<?=$data->id?>"><?=$data->name?></option>
										    <?
										}
								    }
								}
								else
									break;
		            		}				    
						    ?>
						    </select>
						    <br />
						    <label>Модель</label><br />
						    <input class="galaxyin" type="text" placeholder="модель" value="<?$data_g->model?>" name="model" title="Сюда ввдедите модель" pattern="[a-zA-Zа-яА-ЯЁё0-9]{1}[a-zA-Zа-яА-ЯЁё0-9\s]{0,49}" required>
						    <br />
						    <label>Грузоподъёмность</label><br />
						    <input class="galaxyin" type="number" placeholder="грузоподъёмность" value="<?$data_g->capacity?>" name="capacity" title="Сюда ввдедите грузоподъёмность" pattern="[0-9]{1,11}" required>
						    <br />
						    <input class="galaxybutton" name="add" type="submit" value="Добавить">
						    </form>