<!DOCTYPE html>
<html>
	<head>
		<title>Space</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"> <!--описание контента-->
		<link rel="stylesheet" type="text/css" href="http://space.tpmongo/css/space.css" />
		<link rel="stylesheet" type="text/css" href="http://space.tpmongo/css/Animation.css" />
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	</head>
	<body>		
		<header>
			<p id="headp">
				<a href="http://space.tpmongo" id="heada" title="Главная">НЕМНОГО О КОСМОСЕ</a>
			</p>
		</header>
		<nav>
		  <ul>
		    <li><p class="navig">Скопления галактик</p>
		    	<ul>
		     		<li><a href="http://space.tpmongo/cluster" class="navig">Посмотреть</a></li>		
		     		<li><a href="http://space.tpmongo/cluster/insert" class="navig">Добавить</a></li>	
		     		<li><a href="http://space.tpmongo/cluster/excel" class="navig">Записать скопления в Excel</a></li>
				</ul>
		    </li>
		    <li><p class="navig">Галактики</p>
		      	<ul>
		      		<li><a href="http://space.tpmongo/galaxy" class="navig">Посмотреть галактики</a></li>		
		     		<li><a href="http://space.tpmongo/galaxy/insert" class="navig">Добавить галактику</a></li>	
		     		<li><a href="http://space.tpmongo/galaxy/type" class="navig">Посмотреть типы галактик</a></li>
		     		<li><a href="http://space.tpmongo/galaxy/excel" class="navig">Записать галактики в Excel</a></li>	
		      	</ul>
		    </li>
		    <li><p class="navig">Чёрные дыры</p>
		      <ul>
		      		<li><a href="http://space.tpmongo/blackhole" class="navig">Посмотреть</a></li>		
		     		<li><a href="http://space.tpmongo/blackhole/insert" class="navig">Добавить</a></li>	
		     		<li><a href="http://space.tpmongo/blackhole/type" class="navig">Посмотреть типы чёрных дыр</a></li>	
		     		<li><a href="http://space.tpmongo/blackhole/excel" class="navig">Записать чёрные дыры в Excel</a></li>	
		        </ul>
		    </li>
		    <li><p class="navig">Звёздные системы</p>
		    	<ul>
		        	<li><a href="http://space.tpmongo/solarsystem" class="navig">Посмотреть</a></li>		
		     		<li><a href="http://space.tpmongo/solarsystem/insert" class="navig">Добавить</a></li>
		     		<li><a href="http://space.tpmongo/solarsystem/excel" class="navig">Записать звёздные системы в Excel</a></li>
		      	</ul>
		    </li>
		    <li><p class="navig">Звёзды</p>
		    	<ul>
		        	<li><a href="http://space.tpmongo/star" class="navig">Посмотреть</a></li>		
		     		<li><a href="http://space.tpmongo/star/insert" class="navig">Добавить</a></li>
		     		<li><a href="http://space.tpmongo/star/type" class="navig">Посмотреть типы звёзд</a></li>
		     		<li><a href="http://space.tpmongo/star/excel" class="navig">Записать звёзды в Excel</a></li>		        	
		      	</ul>
		    </li>
		    <li><p class="navig">Планеты</p>
		    	<ul>
		        	<li><a href="http://space.tpmongo/planet" class="navig">Посмотреть</a></li>		
		     		<li><a href="http://space.tpmongo/planet/insert" class="navig">Добавить</a></li>	
		     		<li><a href="http://space.tpmongo/planet/type" class="navig">Посмотреть типы планет</a></li>	 
		     		<li><a href="http://space.tpmongo/planet/excel" class="navig">Записать планеты в Excel</a></li>       	
		      	</ul>
		    </li>
		  </ul>
		</nav>  

		<div>
			<? echo $this->getContent() ?>
		</div>
		


	</body>
</html>