<?
	if (isset($planets))
	{
		foreach ($planets->items as $planet) {
			$id = $planet->_id;
			$name = $planet->name;
			$weight = $planet->weight;
			$solar_system = SolarSystem::findById($planet->solar_system_id);
			$type = TypeOfPlanet::findById($planet->type_id)->name;

			include "article.phtml";
		}
		echo "<footer>";
		for ($i=1; $i <= $planets->total_pages; $i++) 
			include "foot.phtml";
		echo "</footer>";
	}
	else
		echo '<article class="midl"><h2>Планет нет</h2></article>';
?>