<?
	if (isset($galaxies))
	{
		foreach ($galaxies->items as $galaxy) {
			$id = $galaxy->_id;
			$name = $galaxy->name;
			$size = $galaxy->size;
			$cluster = Cluster::findById($galaxy->cluster_id);
			$type = TypeOfGalaxy::findById($galaxy->type_id);

			include "article.phtml";
		}
		echo "<footer>";
		for ($i=1; $i <= $galaxies->total_pages; $i++) 
			include "foot.phtml";
		echo "</footer>";
	}
	else
		echo '<article class="midl"><h2>Скоплений галактик нет</h2></article>';
?>